#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - dev
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- src\packages -> src\**\packages.config
- Setup -> setup.cake
- Tools -> build.ps1